// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_gM7m6uqARn9Di-usapEKt-tZlSqrCRE',
    appId: '1:931287240100:web:d320844bdff8782f314531',
    messagingSenderId: '931287240100',
    projectId: 'utme-pass-at-once-36340',
    authDomain: 'utme-pass-at-once-36340.firebaseapp.com',
    storageBucket: 'utme-pass-at-once-36340.firebasestorage.app',
    measurementId: 'G-K2GJ1PFT57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxjimWKPvQL8-JygnSYV6ZlrVRHvYQDU',
    appId: '1:931287240100:android:cb5a82f2d8fed85c314531',
    messagingSenderId: '931287240100',
    projectId: 'utme-pass-at-once-36340',
    storageBucket: 'utme-pass-at-once-36340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTWh-qkPFC3ouam0QMd_8-ns7DVY1fLg',
    appId: '1:931287240100:ios:70e0d53e6f853a76314531',
    messagingSenderId: '931287240100',
    projectId: 'utme-pass-at-once-36340',
    storageBucket: 'utme-pass-at-once-36340.firebasestorage.app',
    iosBundleId: 'com.example.utmePassAtOnce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTWh-qkPFC3ouam0QMd_8-ns7DVY1fLg',
    appId: '1:931287240100:ios:70e0d53e6f853a76314531',
    messagingSenderId: '931287240100',
    projectId: 'utme-pass-at-once-36340',
    storageBucket: 'utme-pass-at-once-36340.firebasestorage.app',
    iosBundleId: 'com.example.utmePassAtOnce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_gM7m6uqARn9Di-usapEKt-tZlSqrCRE',
    appId: '1:931287240100:web:c7c95901ee5da01d314531',
    messagingSenderId: '931287240100',
    projectId: 'utme-pass-at-once-36340',
    authDomain: 'utme-pass-at-once-36340.firebaseapp.com',
    storageBucket: 'utme-pass-at-once-36340.firebasestorage.app',
    measurementId: 'G-2BBDWHLRK7',
  );
}
